version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - gateway-service
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - gateway-service
    networks:
      - microservices-network

  gateway-service:
    build: ./gateway-service
    ports:
      - "3003:3003"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge